### ISSUE TITLE
AOT Compiling in Angular 6 causes the LocalStorage Module to go missing

### ISSUE THREAD

**Issue by darthmolen** [cyrilletuzi/angular-async-local-storage#41] opened 2018-07-25 13:30 UTC
Angular 6 app. Works in dev mode. However, we were getting errors in the console when deploying our app using v6 of this component. Enabled source maps to figure out what was going on and found out that the library is missing after the application is AOT compiled.

![image](https://user-images.githubusercontent.com/533340/43203636-695493a0-8fe4-11e8-9c57-dfb9ab01ae9c.png)

When aot compiling for angular, the library goes missing.

In Dev Mode:

![image](https://user-images.githubusercontent.com/533340/43203672-78d61f4c-8fe4-11e8-90a2-ecb59a26ced4.png)

After AOT compiled.

![image](https://user-images.githubusercontent.com/533340/43203724-9a3b2e52-8fe4-11e8-8add-ed14e284cea3.png)

I'm including our package.json and angular.json

[ClientApp.zip](https://github.com/cyrilletuzi/angular-async-local-storage/files/2228067/ClientApp.zip)

**Comment by cyrilletuzi** [comment] 2018-07-25 14:39
Thanks for reporting this issue and for the details. I can't reproduce it yet with a classic build, I'll investigate more.

A few questions : 
- build tool has been changed in RC2, and so the files names and directories, did you try to remove `node_modules` and to do a new `npm install`?
- I see there is lazy-loading in your example, and it could concern the issue, can you tell me if you use `LocalStorage` of the lib only in lazy-loaded modules, or is it also used in a module eagerly loaded in the `AppModule`?

**Comment by cyrilletuzi** [comment] 2018-07-25 17:42
Tested the second scenario (only in a lazy-loaded module), it works.

@darthmolen Waiting for you to test with a full reinstallation, as installations problems happen often, to not investigate hours for nothing.

By the way, do you use `npm` or `yarn`?

**Comment by darthmolen** [comment] 2018-07-25 19:12
I'll delete my node_modules and do a new npm install and let you know. I did do an upgrade from 5 to 6.

**Comment by alignsoft** [comment] 2018-07-25 20:37
If you’re upgrading from 5 to 6, did you remove the Import?

Then, for versions 4 & 5 only, include the LocalStorageModule in your app root module (just once, do NOT re-import it in your submodules). Since version 6, this step is no longer required and LocalStorageModule is removed.

import { LocalStorageModule } from '@ngx-pwa/local-storage'; @NgModule({ imports: [ BrowserModule, LocalStorageModule, ...   ] ... }) export class AppModule {}

Best,
:Steve

Stephen R. Smith

Alignsoft
447 Nelson Ave, Burlington, Ontario, Canada, L7S 1N3
P : 905.464.4440   

ssmith@alignsoft.com
http://www.alignsoft.com

**Comment by darthmolen** [comment] 2018-07-25 21:01
I deleted my node_modules, did a yarn install --force and then an npm install for grins and giggles. Still works in non-prod mode, but --prod, the module no longer exists in the sourcemap, and comes in as null in the constructor. It's like it doesn't exist to ng build and webpack. I went ahead and zipped up the source so you can see for yourself, there's nothing sensitive in there. https://www.dropbox.com/s/woii6ungmtujj4c/PF.Server.WebUI.zip?dl=0

**Comment by cyrilletuzi** [comment] 2018-07-26 08:20
Thanks for the files. You can now delete them for safety.

Found the issue: it's because your way of defining constructors is quite strange:
```typescript
constructor()
constructor(private localStorage?: LocalStorage) {}
```

Just do the normal way:
```typescript
constructor(private localStorage: LocalStorage) {}
```
and then it works.

I suppose what happens is that tree-shaking happening in `prod` mode doesn't understand your way of defining `constructor` parameters, as they are normally handled by Angular dependency injection, and then thinks the param is not used or not defined and so deletes it for performance.

Closing as it's not related to the lib, but I would be interested to know if there is a reason for this way of defining your constructor?

**Closed by cyrilletuzi** 2018-07-26 08:20 UTC
Labels: bug

**Comment by darthmolen** [comment] 2018-07-26 11:38
I'll work through changing that then. The reason the constructor was that way was that I wanted to use it as a standard business object as well for when dependency injection wasn't involved and I simply needed a clone for serialization or other work.

**Comment by cyrilletuzi** [comment] 2018-07-26 12:07
Thanks for the info.

**Comment by darthmolen** [comment] 2018-07-27 13:51
@cyrilletuzi For informational purposes, looks like they might add that feature to angular :) (nullable types still being respected by the transpiler) https://github.com/angular/angular/issues/25151
