### ISSUE TITLE
ng update (ver 8 -> ver 9) did not work 

### ISSUE THREAD

**Issue by saranglakare** [cyrilletuzi/angular-async-local-storage#359] opened 2020-05-08 13:16 UTC
# Description of the issue
I updated from ver 8 to ver 9. `ng update` failed with message `Migration failed: Cannot read property 'kind' of undefined`.

# Data loss
I read the migration guide in file `MIGRATION_TO_V9.md`. It says to look for `StorageModule.forRoot` and ensure `IDBNoWrap` is set to `false` for backward compatibility. The guide mistakenly seems to suggest _If you do not see IDBNoWrap at all, you are fine_. In my project, there was no such configuration. In fact, `StorageModule` was never loaded at module level. It was directly imported into the component that was using it.

When I upgraded to v9, all my local storage data wiped out as mentioned in the migration guide. Upon digging more, I found that I had to set `IDBNoWrap` to `false` explicitly. If I did that, the data is read in properly.

Now my issues / suggestions:

- Please update the migration guide and ask users to explicitly add the option if they want to avoid losing data (in cases where there is not `IDBNoWrap` option setup at module level in v8)

- Please let me know how to move data to newer version so we can do this migration one time for user data and never have to worry about the `IDBNoWrap` option again.

Thanks!

**Comment by cyrilletuzi** [comment] 2020-05-08 13:33
Thanks for the report.

I'll look into the `ng update` failure. I may need additional information.

On the other hand, the migration guide is accurate:
- nowhere I can find your quote "If you do not see IDBNoWrap at all, you are fine", the guide explains how to check the work done by `ng update`, and given the configuration you tell me (ie. there was no `StorageModule` imported at all), it means you're in the case where the guide says `you should see StorageModale.forRoot({ IDBNoWrap: false })`,
- it also says "If ng update didn't work as expected, please file an issue.", not "If ng update fails, go live".

Nevertheless, I'll try to make the guide more comprehensible.

**Comment by cyrilletuzi** [comment] 2020-05-08 13:39
> Please let me know how to move data to newer version so we can do this migration one time for user data and never have to worry about the IDBNoWrap option again.

About that part: unfortunately, that is impossible, and it is why there is the `IDBNoWrap` option to manage backward compatibility. Indeed, as the data is stored in each user browser, there is no way to plan a global migration here.

**Comment by cyrilletuzi** [comment] 2020-05-08 13:49
I can't reproduce your `ng update` failure, so I'll need more information:
- exact version of your *global* Angular CLI
- versions of all your Angular packages in your project (result of `ng version`)

**Comment by saranglakare** [comment] 2020-05-15 07:28
> nowhere I can find your quote "If you do not see IDBNoWrap at all, you are fine", 

Yes, that's how I interpreted the guide since it does not mention the case when `IDBNoWrap` setting was missing (which was my case).

> it means you're in the case where the guide says "you should see `StorageModale.forRoot({ IDBNoWrap: false })`",

Yes, but that's implicit for you since you are the author :-) I thought since there is no such setting, I don't have to worry about it. My misinterpretation, yes, but I guess many others may read it that way.

**Comment by saranglakare** [comment] 2020-05-15 07:32
> About that part: unfortunately, that is impossible, and it is why there is the `IDBNoWrap` option to manage backward compatibility. Indeed, as the data is stored in each user's browser, there is no way to plan/do a global migration here.

My experience was data was lost when I updated something. Otherwise, even with the `IDBNoWrap` set to `True`, I was able to access the old data. I believe it was under a `value` key. I was thinking of a simple function that would move over the data from the `value` key into memory, wipe the storage, and then re-add it. Thoughts?

**Comment by saranglakare** [comment] 2020-05-15 07:35
> I can't reproduce your `ng update` failure, so I'll need more information:
> 
> * exact version of your _global_ Angular CLI
> * versions of all your Angular packages in your project (result of `ng version`)

Sorry I don't have that setup anymore. However, I remember I was on Angular 9.1.4 when I did this update. My wild guess is the lack of `IDBNoWrap` or `StorageModale.forRoot` in my configuration caused the problem? Somewhere I remember reading that you had asked `StorageModale.forRoot` to be there when installing the previous version. However, in my setup, there was no such thing.

**Comment by cyrilletuzi** [comment] 2020-05-15 08:49
The confusion about the migration guide is because you used it to *do* the migration by yourself, while its goal is just to *check* if `ng update` did its work correctly. I added instructions to emphasize to delay the migration if `ng update` did not work.

> My experience was data was lost when I updated something. Otherwise, even with the IDBNoWrap set to True, I was able to access the old data. I believe it was under a value key. I was thinking of a simple function that would move over the data from the value key into memory, wipe the storage, and then re-add it. Thoughts?

Indeed, but how will you know that all the app users have opened the app and so that the data was migrated for all users?

> My wild guess is the lack of IDBNoWrap or StorageModale.forRoot in my configuration caused the problem? Somewhere I remember reading that you had asked StorageModale.forRoot to be there when installing the previous version. However, in my setup, there was no such thing.

Nope, it is a legit case and the schematics are planned to handle it. I did again this migration scenario when you posted the issue and all worked as intented.

Given the error message, it is more likely an issue with Angular packages version. It often happens that some Angular sub-packages (like `@angular-devkit/***`) are not in sync when doing a major migration. And schematics rely on this kind of packages. I've added instructions to ask to check that before upgrading the lib.

Unfortunately, if you can't reproduce the issue anymore, I'll close the issue as there is nothing actionnable right now. If you were to reproduce the issue, please open a new issue.

**Closed by cyrilletuzi** 2020-05-15 08:49 UTC
Labels: needs repro
