### ISSUE TITLE
TypeError: Cannot read property 'keys' of undefined

### ISSUE THREAD

**Issue by sebaherrera** [cyrilletuzi/angular-async-local-storage#97] opened 2019-03-29 19:50 UTC
Hi, I'm trying to get keys inside a service with the following code:

import { LocalStorage, JSONSchema } from '@ngx-pwa/local-storage';

....

constructor(private http: HttpClient, protected localStorage: LocalStorage) { }

.....

this.localStorage.keys().subscribe((keys) => {

  console.log(keys);

});

But I'm getting "TypeError: Cannot read property 'keys' of undefined". If I use it on a component, with exactly the same code, it works right. It's the only thing that's preventing me to implement the full API on my website.

Angular CLI: 7.3.7
Node: 11.9.0
OS: win32 x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cli                      7.3.7
@angular/pwa                      0.13.7
@ngtools/webpack                  7.3.7
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

**Comment by cyrilletuzi** [comment] 2019-03-30 08:35
Hi, what version of the lib are you using?

**Comment by sebaherrera** [comment] 2019-03-30 12:55
It is 7.4.2. I tried the feature when you launched it, but cannot isolate the issue until now.

I'll try with v8 beta in the upcoming week, because it is now incompatible with my ad-hoc code to retrieve keys (native IndexedDB).

**Comment by cyrilletuzi** [comment] 2019-04-03 10:13
@sebaherrera In which browser is the issue happening? It could be the same issue as in #95, which happens only in Firefox.

**Comment by sebaherrera** [comment] 2019-04-03 18:57
I tried it in Chrome. But it's strange that it only fails when used inside Angular services, not components.

**Comment by cyrilletuzi** [comment] 2019-04-04 07:37
While the issue is different, #95 happens in the same scenario. Unfortunately I can't reproduce your issue. I added an e2e test in v8 with usage in a service, and it works. I've also done that from a long time in my own apps.

So I will need a full reproduction of the issue (on Stackblitz for example).

**Comment by sebaherrera** [comment] 2019-04-09 23:59
Hi. Sorry about the delay. I cleaned up a mess of observables and now it works right.

Thanks again for your help!

**Comment by cyrilletuzi** [comment] 2019-04-10 07:34
OK, closing then.

**Closed by cyrilletuzi** 2019-04-10 07:34 UTC
Labels: needs repro
