### ISSUE TITLE
Extension settings

### ISSUE THREAD

**Issue by n2pro** [cyrilletuzi/angular-async-local-storage#55] opened 2018-11-14 11:04 UTC
Hello, good library!
I would like to be able to select the storage.
Could you add in LocalStorageProvidersConfig and consider this option in localDatabaseFactory.
If you do not make it difficult to do it yourself or i can do it pull request ?

**Comment by cyrilletuzi** [comment] 2018-11-14 18:24
@n2pro Hi Nikolai, can you explain your use case?

The goal of the lib is to use `indexedDb` in all cases possible, as it's better for performance. If you want to stick to `localStorage`, then the native browser API is enough and no lib is needed.

Or is it because you want to implement another type of storage?

**Comment by cyrilletuzi** [comment] 2018-11-21 18:19
Closing for cleaning purpose, as there is no answer. Feel free to comment and I'll reopen the issue.

**Closed by cyrilletuzi** 2018-11-21 18:19 UTC

**Comment by hamzaiqbal** [comment] 2019-03-01 17:41
Hello,

I'm interested in this feature because I have an issue on IE11 and the library is not falling back correctly on localstorage. 
I'm just subscribing to the getItem method :
 `this.localStorage.getItem<MyModel>('somekey').subscribe(model => {  console.log(model); });`
It generates an Error : Object doesn't support this action
<img width="1239" alt="2019-03-01_183346" src="https://user-images.githubusercontent.com/6388438/53655612-f8290980-3c50-11e9-8d0a-346a35adbdd4.png">

Library version : 7.4.0
Angular version : 7.1.0
Typescript version : 3.1.6

**Comment by cyrilletuzi** [comment] 2019-03-01 18:21
@hamzaiqbal Thanks for your feedback.

You don't want to select the storage: you want the fallback to work.

I would need a reproduction of the issue to help you, as all tests are working, including in private mode.

**Comment by hamzaiqbal** [comment] 2019-03-04 09:28
@cyrilletuzi Thank you for your quick answer. A weird thing happend : The library works again after a computer restart while nothing was happening during a ng serve... I changed nothing in my code since Friday.
We can leave that issue closed, I will notice you if this problem happens agains.

**Comment by hamzaiqbal** [comment] 2019-03-04 09:37
@cyrilletuzi Now I remember that I tried a fix : https://github.com/angular/zone.js/issues/1001#issuecomment-360833630
That certainly resolved the issue on my computer (whence the restart), that could be a lead.

**Comment by cyrilletuzi** [comment] 2019-03-04 17:44
@hamzaiqbal Does the complete error message/trace tell what are the object and action not available?

**Comment by hamzaiqbal** [comment] 2019-03-05 09:33
I'm sorry, I lost the error trace while I can't reproduce it. I will contact you if it happens again.
