### ISSUE TITLE
Potential issue when with large amounts of data?

### ISSUE THREAD

**Issue by peder1001** [cyrilletuzi/angular-async-local-storage#395] opened 2020-07-07 14:58 UTC
# Checks before posting an issue

- [x ] I have read all the library's documentation (README, CHANGELOG, MIGRATION and /docs)
- [x ] I understand I am writing to a *human being*, doing this open source project on his *free* time
- [x ] I will be involved in my own issue, by answering questions and informing if the issue is resolved

# Configuration

- `@ngx-pwa/local-storage` version: **9.0.2**
- Angular version (`ng version`): **9.0.1**
```
Copy the result here
```

# Description of the issue
I have beeing using this for about 30k-60k array objects with no problems.
Now I have a larger data set of about 370k array objects, and I have run into a problem.

storage.set throws an error, and there is no error message.
The data does not get stored in indexedDb because it does not get set (due to the error).

key:
![image](https://user-images.githubusercontent.com/6201162/86800056-eccec500-c072-11ea-907d-58b745f645f8.png)
--
data:
![image](https://user-images.githubusercontent.com/6201162/86799632-729e4080-c072-11ea-9500-414626ac14e4.png)

Then:
no error:
![image](https://user-images.githubusercontent.com/6201162/86799594-6a460580-c072-11ea-9981-62c67f06aa76.png)

Any ideas about what the issue could be?

**Comment by peder1001** [comment] 2020-07-07 15:06
By the way, just tested with 200k array objects, and that seemed to work fine.
![image](https://user-images.githubusercontent.com/6201162/86801385-3b309380-c074-11ea-8eda-6b56fcdafc69.png)

**Comment by cyrilletuzi** [comment] 2020-07-07 18:13
Hi @peder1001 , I'm quite busy this week, could you setup a repo with a reproduction so I can test easily?

Also, can you tell in which browser and version exactly you are testing (as it could be related to browsers limitations)?

**Comment by peder1001** [comment] 2020-07-07 18:40
No problem. Will setup a reproduction for you.

Chrome Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by peder1001** [comment] 2020-07-07 21:17
Setup a simple test repository for you and sent you an invite.

**Comment by cyrilletuzi** [comment] 2020-07-11 09:10
Hi @peder1001, thanks for the repo.

So:
- `success` callback with Firefox latest stable (v78)
- `success` callback with Edge Beta (Chromium v84) and with Chrome Canary (v86)
- `error` callback with Edge and Chrome stable (v83), but indeed with `error` being `null`

So we can first say the lib is not faulty, the issue is on the browser side. It's just not sure if it is a Chromium bug resolved in v84 or if it is a normal memory limitation in stable versions. We'll have to wait for the v84 stable release to be sure. But in both cases, the lib won't be able to do anything about it. I'll just add some documentation about browsers size limits if it is relevant.

The only detail where the lib behavior may be incorrect is `error` being `null`. Managing `error` in `catch` clauses is quite a mess in JS as there is no typing and the `error` object is not always the same, so I'll check that.

**Comment by cyrilletuzi** [comment] 2020-07-11 09:39
I confirm it is an intended size limits in browsers, Chrome is throwing `The serialized keys and/or value are too large (size=141283343 bytes, max=133169152 bytes).`.

Currently investigating why the error message is not propagated by the lib.

**Comment by peder1001** [comment] 2020-07-11 09:43
Ok! Great to know the limitation. Will probably have to split the data up into multiple keys in that case. Thanks for checking, and good you found something new :)

**Closed** 2020-07-11 10:32 UTC
Labels: depends on another project

**Comment by cyrilletuzi** [comment] 2020-07-11 10:40
This is fixed in v10.0.1.

Thanks for your helpful report. :)

This lib (and my other open source projects) are done during my free time, so consider to help by [sponsoring](https://github.com/sponsors/cyrilletuzi), or to ask your company to.
