### ISSUE TITLE
Update instead of Add? – re: Error: IndexedDB setter issue : Key already exists in the object store

### ISSUE THREAD

**Issue by alignsoft** [cyrilletuzi/angular-async-local-storage#47] opened 2018-09-25 18:19 UTC
This is more of a question as to the correct approach to updates to data in the local store, not an issue or a bug, so my apologies if this isn't the correct venue.

I'm running into this error (correctly, I might add):

`error occured setting data in the local store Error: IndexedDB setter issue : Key already exists in the object store
`
This occurs where I've set a key in the store, and then later am trying to reset a value for the same key, and it throws the above error. I can't anticipate when the user will navigate through a specific workflow that will cause a value to be fetched from over the network and re-added to the local store, so I'm trying to determine the best way to handle this.

My understanding is we can only add, not update(put) an object into the store, which brings me to the question of how to handle updates. Ideally I would like to update by default any existing value for a key already in the store, but failing that, is the accepted approach to always test for the presence of a key, and if it exists, to delete it first, then add the new value with that key?

**Comment by cyrilletuzi** [comment] 2018-09-25 19:51
@alignsoft `setItem` should either add or update, the library is taking care of this. So it's an issue, this error should not appear.

But to fix this, I need information:
- can you share the code where it happens?
- is it reproducible in a systematic way? 
- any special context (private mode, special browser settings, etc.)?

One possible problem could be concurrency: do you know if the first `setItem` and the second one happen at the same time?

**Comment by cyrilletuzi** [comment] 2018-09-25 19:54
One other possible problem: do you store special values like falsy values (empty string, `0`, `null`, `undefined`...)?

**Comment by cyrilletuzi** [comment] 2018-09-25 20:05
After some tests, I think my first suggestion could be the right one: if you don't wait the end of the first `setItem`, the second one could still add instead of update as the data is not up to date...

**Comment by alignsoft** [comment] 2018-09-25 20:32
The keys are constructed from attributes passed to functions, and there are some that are undefined, so I may have a key like 'SomethingSomeOtherThingOneMoreThingundefinedundefined', and the values will be Objects, either {value: 1}, or in the event the fetched data returns an error, then the store gets passed an empty object {}.

I'm going through now and modifying the key constructor so it builds the keys from "attributeOne || '' " + "attributeTwo || '' ", instead of just attributeOne + AttributeTwo, which will eliminate the undefined strings from the key.

I'm not sure that it is a concurrency issue, as a number of the keys were set when the app first initialized, and then they were included in a manually fired process to fetch a number of values and save them into local storage, which is where I tripped over the existing keys, but I was able to verify that the keys were in the store before I fired the process that tried to add them again.

The meat of the code is here:

`     var fromComponent: string = "valLists" + (category || '') + (qualifier || '') + (langCd || '1');`


`     returnValue = this.httpClient.get(SERVER_API, { params: params })
`
```
    returnValue
    .subscribe(
    data => {
        if (data.error) {
            console.log("Error returned: ", data.error);
            let emptyObject = {};
            // Store object in localstorage as clear-text object
            this.localStorage.setItem(SERVICE_NAME + fromComponent, emptyObject).subscribe(() => {/* Success */ }, (data) => { console.log("An error occured setting data in the local store", data, fromComponent) });
        } else {
            this.localStorage.setItem(SERVICE_NAME + fromComponent, data).subscribe(() => {/* Success */ }, (data) => { console.log("An error occured setting data in the local store", data, fromComponent) });
        }
    })
```

**Comment by alignsoft** [comment] 2018-09-25 21:36
In my app.module, in @NgModule{} 

```
    LocalStorageModule.withConfig({
      prefix: 'asi-dev',
      storageType: 'localStorage'
    }),
```

On App Init, I call that same service - I have a set list of value list codes that I iterate over and fetch the values one at a time, and when the service fetches them from the db, they're stored automagically in localstorage. On Init, I pass a half dozen very commonly used value list codes through that service so they're cached early on, and then if I'm going to take the app offline, I pass a full list of all the value list codes to the same service so that they're all fetched and cached, and then I can return them from the cache if the network isn't present.

If I exclude the keys I've already fetched at startup from the longer list of keys, then I can avoid the issue, however I should be getting the most up to date values from the database when I take the app offline, and ideally update those that I've already fetched but may be stale.

**Comment by cyrilletuzi** [comment] 2018-09-26 08:46
@alignsoft Where does `withConfig` come from? It doesn't exist in this lib.

**Comment by alignsoft** [comment] 2018-09-26 13:42
Ah - sorry - that's from another localstorage/sessionstorage library (that doesn't use indexedDb).

**Comment by cyrilletuzi** [comment] 2018-09-26 17:13
@alignsoft Do we agree this issue is related to this lib and not the other one?

**Comment by alignsoft** [comment] 2018-09-26 17:32
Yes - this issue is definitely not related to the other lib - it's an indexeddb error being thrown, and the other implementation is just a front end on the browsers local/session storage that's accessed differently.

`import { LocalStorage } from '@ngx-pwa/local-storage';
`
//in constructor
`protected localStorage: LocalStorage
`
//in use
`this.localStorage.setItem`

**Comment by joeskeen** [comment] 2018-09-26 18:01
I have the same issue, but I was able to work around it this way:

```typescript
    async set<T>(key: string, value: T): Promise<void> {
        try {
            await this.localStorage.setItem(key, value).toPromise();
        } catch (err) {
            await new Promise(resolve => setTimeout(resolve, 250));
            await this.set(key, value);
        }
        console.info('PreferencesService.set', key, value);
    }
```

Thus it does seem to be a concurrency issue.

**Comment by cyrilletuzi** [comment] 2018-09-26 19:12
@joeskeen Thanks for your info. It's not normal you have to do that.

I indeed spotted a concurrency issue in the lib. Will release a beta in the next minutes.

**Comment by cyrilletuzi** [comment] 2018-09-26 19:29
@alignsoft @joeskeen @santanageorge @jsilvazuniga Could you test with:

`npm install @ngx-pwa/local-storage@6.1.1-beta.0`

Thanks.

**Comment by cyrilletuzi** [comment] 2018-09-26 19:39
To be exact:
1. please check if there is still an error,
2. if it's OK, please also check that data is what you want it to be at the right time, in all scenarios.

Indeed, the beta version is now avoiding a concurrency issue when 2 `setItem` are concurrent. But half of the issue is in your code, as this situation should *not* happen. All methods of this lib are asynchronous, so you should always wait for operations to complete, so things happen is the right order.

**Comment by alignsoft** [comment] 2018-09-27 14:31
Updating now and will test over the next few hours.

**Comment by alignsoft** [comment] 2018-09-28 16:02
So far, so good. I haven't had the 'Key already exists' error reoccur, and it appears the data I'm storing is what I'm expecting. My testing involves calling a set of services 530 times (each fetch is in a promise, which is pushed into an array of fetch promises and fired with `Promise.all([array-of-promises])`, and storing the resulting data each with it's own key. When it completes, I fire it again and overwrite the original data.

**Comment by cyrilletuzi** [comment] 2018-09-29 08:10
Released in stable.

Thanks all for your feedback, it was a previously reported issue, but as I had no feedback in the previous reports, I wasn't able to spot the problem.

@alignsoft Thanks for testing.

@joeskeen Let me know if there is still a problem when you'll test.

**Closed by cyrilletuzi** 2018-09-29 08:10 UTC
Labels: bug

**Comment by joeskeen** [comment] 2018-10-01 23:06
Just tested it, it's working great now!  Thanks @cyrilletuzi for the quick fix!
