### ISSUE TITLE
Error with localStorage.setItem IE11

### ISSUE THREAD

**Issue by tosun-si** [cyrilletuzi/angular-async-local-storage#23] opened 2018-02-21 18:44 UTC
Hello, sorry for disturbing you,

Firtsly, thanks for this API.

I work on an Angular 5 project with the following version of this API : "angular-async-local-storage": "^3.1.1".

I am putting a Json object in the local storage : 

this.localStorage.setItem("key", localStorageTokenInfo)

In chrome, there is no problem, but on IE11, i have the following error : 

"indexedDb setter issue : undefined"

In the https://www.npmjs.com/package/angular-async-local-storage page, it is indicated that IE10+ is compatible with this API and IndexDb.

Can you help me please ?

**Comment by cyrilletuzi** [comment] 2018-02-21 22:55
Hi, yes, the library is tested in IE11 so it should work. But I need a reproduction of this issue, I can't help without it.

You should first check permissions in your IE : problems in IE have already been reported and for now it was always because of permissions issues. Options are : 
- is using IndexedDB API directly working ?
- try to reset all the settings of IE to defaults.

**Comment by cyrilletuzi** [comment] 2018-03-11 14:58
As there is still no reproduction and no more news, I'll close this issue, but feel free to comment if there is anything new.

**Closed by cyrilletuzi** 2018-03-11 14:58 UTC
Labels: bug
