### ISSUE TITLE
Issues with object store after clearing browsing data

### ISSUE THREAD

**Issue by gimmeshelter** [cyrilletuzi/angular-async-local-storage#1007] opened 2024-04-16 20:19 UTC
# Checks before posting an issue

- [x] I have read _all_ the library's documentation:
  - [README](https://github.com/cyrilletuzi/angular-async-local-storage/blob/main/README.md)
  - [CHANGELOG](https://github.com/cyrilletuzi/angular-async-local-storage/blob/main/CHANGELOG.md)
  - [MIGRATION](https://github.com/cyrilletuzi/angular-async-local-storage/blob/main/MIGRATION.md)
  - [/docs](https://github.com/cyrilletuzi/angular-async-local-storage/tree/main/docs)
- [x] I have checked in already:
  - [opened issues](https://github.com/cyrilletuzi/angular-async-local-storage/issues)
  - [closed issues](https://github.com/cyrilletuzi/angular-async-local-storage/issues?q=is%3Aissue+is%3Aclosed)
  - [questions answered](https://github.com/cyrilletuzi/angular-async-local-storage/discussions/categories/q-a) in the new "Discussions" tab
- [x] I understand I am writing to a *human being*, doing this project *unpaid*
- [x] I will be involved in my own issue, by answering questions and informing if the issue is resolved

# Configuration
- `@ngx-pwa/local-storage` version: 17.0.0
- Angular version (`ng version`): 17.3.3
```
ng version
Node.js version v21.1.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.3.3
Node: 21.1.0 (Unsupported)
Package Manager: yarn 1.22.22
OS: darwin arm64

Angular: 17.3.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.3
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.3.3
@angular-devkit/schematics      17.3.3
@schematics/angular             17.3.3
ng-packagr                      17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

# Description of the issue

Recently during testing, I cleared my browsing data in Chrome (123.0.6312.124) using their Clear Browsing Data utility.  I cleared data for the last hour.  In doing so, Chrome removed the 'localStorage' object store, but not the 'ngStorage' database from IndexedDB.  When I tried to load my app, I started receiving errors like the following: "Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found."  I have tested the scenario repeatedly and always get the same result and the 'localStorage' object store is never recreated.

# How to reproduce the issue

1. Allow the Angular app to create some data in IndexedDB
2. Verify that the `ngDatabase` > `localStorage` items are present in IndexedDB
3. In Chrome, use the "Clear Browsing Data" utility to clear browsing data for the last hour
4. Verify that the `ngDatabase` item exists in IndexedDB, but the `localStorage` object store doesn't exist under `ngDatabase`
5. Refresh your Angular app that uses local-storage and you should see the error noted above and the `localStorage` object store is not recreated under `ngDatabase`

**Comment by cyrilletuzi** [comment] 2024-04-16 21:41
Hello @gimmeshelter, thank you for the helpful report which should allow me to reproduce. I will look into it soon and get back to you.

**Comment by cyrilletuzi** [comment] 2024-04-17 08:14
@gimmeshelter I have a few questions:
- what is your OS?
- what is your version of Chrome?
- which checkbox items are checked and not checked when you do "Clear browsing data"?
- do you have to wait at least one hour has passed to reproduce the issue or not?

Asking these questions because I cannot reproduce on my side: when I clear browsing data in Chrome, both the `localStorage` object store and the `ngDatabase` database are deleted by Chrome.

**Comment by cyrilletuzi** [comment] 2024-04-17 16:19
> I can no longer reproduce this despite reproducing 20x throughout the day yesterday. I am willing to call it a fluke and close.

Has your Chrome version changed since? There was the v124 update yesterday/today.

**Comment by gimmeshelter** [comment] 2024-04-17 17:33
> > I can no longer reproduce this despite reproducing 20x throughout the day yesterday. I am willing to call it a fluke and close.
> 
> Has your Chrome version changed since? There was the v124 update yesterday/today.

No.  During testing today, I was still using 123.0.6312.124.  I am in a corporate environment and our updates are centrally controlled, so we're not always on the latest.

**Comment by cyrilletuzi** [comment] 2024-04-17 20:31
Noted.

I will close the issue for now, because in any cases it would be a browser bug. In `indexedDb`, object stores can only be created during the database creation or update. So having the object store deleted by the browser but not the database would cause an impossible situation to solve for libraries and applications.

**Closed by cyrilletuzi** 2024-04-17 20:31 UTC
Labels: needs repro

**Comment by gimmeshelter** [comment] 2024-04-17 20:34
> Noted.
> 
> I will close the issue for now, because in any cases it would be a browser bug. In `indexedDb`, object stores can only be created during the database creation or update. So having the object store deleted by the browser but not the database would cause an impossible situation to solve for libraries and applications.

Understood.  Thank you for looking into it and I apologize for the false alarm.
